### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by tbrittoborges** [dieterich-lab/crc1550-inf-datamanagement#1]
- [ ] Document FASTQ data upload [eg](https://github.com/qbicsoftware/etl-scripts/blob/master/drop-boxes/register-fastq-dropbox-with-metadata/register-fastq-with-metadata-dropbox.py)
- [ ] Document MIAME guidelines [eg](https://www.ncbi.nlm.nih.gov/geo/info/)
- [ ] Document Geo-upload [eg](https://github.com/qbicsoftware/geo-uploader-cli)
